### PR TITLE
Apply black

### PR DESCRIPTION
**Pull request by ulgens**
Black only version of https://github.com/tfoxy/graphene-django-optimizer/pull/62

### CODE REVIEW

**Comment by ulgens** [comment]
@tfoxy I'm not sure why travis is not triggered, I can use some help to fix it.

**Comment by ulgens** [comment]
Other small stuff i found, thinking they relates to this topic:
* CI can be and should be IMO moved to Github Actions.
* We need a CI step to keep styling consistent.
* We need a part in documentation about development.

**Review by wodCZ — APPROVED** [review]
LGTM

**Comment by tfoxy** [comment]
Hi @ulgens! Thanks for the PR. I'm trying to fix the travis configuration. In the meantime, can you add `black` to the travis lint stage? Something like: `black --check graphene_django_optimizer/ tests/ setup.py`. Or maybe we can use the `pyproject.toml` file to configure the files.

**Comment by ulgens** [comment]
Hey man, I definitely add it as a CI step, and we can use Poetry too but I was trying to keep this one short if that's ok for you. We can handle those items in different PRs.

**Comment by tfoxy** [comment]
Ok, seems good. Will merge then.

**Pull request merged**
